### ISSUE TITLE
Please add instructions how to use in swift for beginners (no knowledge of bridging headers)

### ISSUE THREAD

**Issue by mika76** [jcoleman/JCNotificationBannerPresenter#32]

**Comment by jcoleman** [comment]
I haven't yet had the opportunity to use Swift in any of my projects; I'm of course open to pull requests.

**Comment by zdesiree** [comment]
If you want to use it in your Swift project, just install the pod and import it in your Bridging-Header like this
`#import <JCNotificationBannerPresenter/JCNotificationCenter.h>`
If you don't already have a Bridging-Header create one as described here: https://bohemianpolymorph.wordpress.com/2014/07/11/manually-adding-a-swift-bridging-header/

In your Swift files where you want to use the library import it like this:
`import JCNotificationBannerPresenter`

And finally use it like this:
`JCNotificationCenter.enqueueNotificationWithTitle(mytitle, message: mymessage) {}`
