### ISSUE TITLE
Banner slide to left like google hangouts for ios

### ISSUE THREAD

**Issue by krvajal** [jcoleman/JCNotificationBannerPresenter#34]
Can u make the banner work like the Google Hangouts app for iOS?

**Comment by jcoleman** [comment]
If you'd like to contribute a patch that does this, I'm open to considering including it in the project.

If you'd like to pay my consultancy the going market rate to implement the feature, feel free to let me know.

Otherwise this isn't part of this project's roadmap for the foreseeable future.
